#cloud-config

groups:
  - admingroup: [root,sys]
  - cloud-users

users:
  - name: user
    groups: users
    shell: /bin/bash
    sudo: 'ALL=(ALL) NOPASSWD:ALL'
    ssh-authorized-keys:
      - ${ssh_public_key}
      
