all:
  hosts:
    master:
      ansible_host: 84.201.131.131
      access_ip: 84.201.131.131
      ip: 192.168.10.22
      ansible_user: user
    worker1:
      ansible_host: 51.250.15.147
      access_ip: 51.250.15.147
      ip: 192.168.10.26
      ansible_user: user
    worker2:
      ansible_host: 89.169.186.209
      access_ip: 89.169.186.209
      ip: 192.168.11.10
      ansible_user: user
  children:
    kube_control_plane:
      hosts:
        master:
    kube_node:
      hosts:
        master:
        worker1:
        worker2:
    etcd:
      hosts:
        master:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node: